version: '3.8'

services:
  # 1. PostgreSQL
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: "CjofbyoPuzpg"
      POSTGRES_PASSWORD: "!^*gi])Kv2Cr6(;HVw/on68WS"
      POSTGRES_DB: "sweetshop"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # 2. Spring Boot бэкенд
  backend:
    image: zivoru/sweetshop-backend:1.0.5
    container_name: backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://89.104.65.160:5432/sweetshop"
      SPRING_DATASOURCE_USERNAME: "CjofbyoPuzpg"
      SPRING_DATASOURCE_PASSWORD: "!^*gi])Kv2Cr6(;HVw/on68WS"
    ports:
      - "8080:8080"
    restart: unless-stopped

  # 3. Первый React-сайт
  frontend1:
    image: zivoru/sweetshop-frontend:1.0.2
    container_name: frontend
    ports:
      - "8081:81"
    restart: unless-stopped

  # 4. Второй React-сайт
  frontend2:
    image: zivoru/sweetshop-admin:1.0.1
    container_name: frontend-admin
    ports:
      - "8082:82"
    restart: unless-stopped

  # 5. adminer (веб-интерфейс для PostgreSQL)
  adminer:
    image: adminer
    ports:
      - "8083:8080"
    restart: unless-stopped

volumes:
  postgres_data: